name    'jlondon-phpmyadmin'
version '0.1.0'
source 'UNKNOWN'
author 'Justice London'
license 'Apache License, Version 2.0'
summary 'Puppet phpMyAdmin module'
description 'A puppet module which allows you to install and manage phpMyAdmin'
project_page 'http://github.com/justicel/puppet-phpmyadmin'
dependency 'puppetlabs/apache', '>= 0.6.0'
dependency 'puppetlabs/concat', '>= 1.0.0'
