name    'jlondon-phpmyadmin'
version '0.0.3'
source 'UNKNOWN'
author 'Justice London'
license 'Apache License, Version 2.0'
summary 'Puppet phpMyAdmin module'
description 'A puppet module which allows you to install and manage phpMyAdmin'
project_page 'http://github.com/justicel/puppet-phpmyadmin'
dependency 'puppetlabs/apache', '>= 0.4.0'
dependency 'ripienaar/concat', '>= 0.2.0'
